#ifndef BRINGITBACK_CODEFLAGS_HPP
#define BRINGITBACK_CODEFLAGS_HPP

//#define DEV_MODE

#ifdef DEV_MODE

#define DEV_KEEPCONSOLEOPEN
#define DEV_ALLOWCHEATS
#define DEV_STOPTIMER


#endif // DEV_MODE

#endif // BRINGITBACK_CODEFLAGS_HPP